import Foundation

// Phase 3: Loads keyboard layouts from the JSON files generated by
// convert_keyboard_layouts.py.  The JSON files live in Layouts/ inside the
// keyboard extension bundle.
//
// Usage:
//   let layout = LayoutLoader.load("lime_phonetic") ?? .phonetic

final class LayoutLoader {

    // MARK: - JSON Codable types (mirrors the Python converter output)

    private struct JSONLayout: Decodable {
        let id: String
        let defaultWidthPercent: Double
        let rows: [JSONRow]
    }

    private struct JSONRow: Decodable {
        let isBottomRow: Bool
        let keys: [JSONKey]
    }

    private struct JSONKey: Decodable {
        let code: Int
        let label: String
        let sublabel: String
        let widthPercent: Double
        let icon: String
        let isModifier: Bool
        let isRepeatable: Bool
        let isSticky: Bool
        let popupKeyboard: String
        let longPressCode: Int?  // optional: nil if not present in JSON (old layouts)
    }

    // MARK: - Cache

    private static var cache: [String: LimeKeyLayout] = [:]
    private static let lock = NSLock()

    // MARK: - Public API

    /// Load a layout by ID (e.g. "lime_phonetic").
    /// Returns nil if the JSON file is not found or fails to parse.
    static func load(_ id: String) -> LimeKeyLayout? {
        lock.lock()
        if let cached = cache[id] { lock.unlock(); return cached }
        lock.unlock()

        guard let layout = parseFromBundle(id: id) else { return nil }

        lock.lock()
        cache[id] = layout
        lock.unlock()
        return layout
    }

    // MARK: - Private

    private static func parseFromBundle(id: String) -> LimeKeyLayout? {
        // XcodeGen copies the Layouts/ folder contents flat into the bundle root.
        guard let url = Bundle.main.url(forResource: id, withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else { return nil }

        let decoder = JSONDecoder()
        guard let json = try? decoder.decode(JSONLayout.self, from: data) else { return nil }

        let rows = json.rows.map { jr -> KeyRow in
            let keys = jr.keys.map { jk in
                KeyDef(
                    code:          jk.code,
                    label:         jk.label,
                    sublabel:      jk.sublabel,
                    widthPercent:  CGFloat(jk.widthPercent),
                    icon:          jk.icon,
                    isRepeatable:  jk.isRepeatable,
                    isModifier:    jk.isModifier,
                    isSticky:      jk.isSticky,
                    longPressCode: jk.longPressCode ?? 0
                )
            }
            return KeyRow(keys: keys, isBottomRow: jr.isBottomRow)
        }
        return LimeKeyLayout(id: id, rows: rows)
    }

    /// Pre-warm the cache for commonly used layouts in the background.
    static func prefetchCommonLayouts() {
        let ids = [
            "lime_phonetic", "lime_phonetic_shift",
            "lime_abc", "lime_abc_shift",
            "lime_number", "lime_number_symbol",
        ]
        DispatchQueue.global(qos: .background).async {
            for id in ids { _ = load(id) }
        }
    }
}
